### ISSUE TITLE
Error on first run of `stack run`

### ISSUE THREAD

**Issue by IceAsteroid** [alpacaaa/zero-bs-haskell#24]
I followed the step in the wiki where it says

> That's absolutely fine, we'll fix it in a minute. First, we want to run our vanilla stack-generated Haskell project just to check what's going on.
> 
> stack run
> > someFunc
> 
> What's this someFunc business? It's just a poorly worded hello world message. But more importantly, we have compiled and ran a Haskell application!
>

I ran `stack build`, edited the `stack.yaml` and `package.yaml` as described, and then ran `stack run`.

Stack version: `Version 3.1.1, Git revision d8cef4ea052430ea09ce7836c41e68b52d04fd73 x86_64 hpack-0.37.0`.

Here's the output of `stack run`:

```
zero-bullshit> configure
zero-bullshit> Configuring zero-bullshit-0.1.0.0...
zero-bullshit> build with ghc-9.6.6
zero-bullshit> Preprocessing library for zero-bullshit-0.1.0.0..
zero-bullshit> Building library for zero-bullshit-0.1.0.0..
zero-bullshit> [1 of 2] Compiling Paths_zero_bullshit
zero-bullshit> [2 of 2] Compiling Zero.Server
zero-bullshit> 
zero-bullshit> /tmp/stack-c51d5627a8ccab17/zero-bullshit-0.1.0.0/src/Zero/Server.hs:172:37: error: [GHC-68441] [-Wdeprecations, Werror=deprecations]
zero-bullshit>     In the use of ‘params’ (imported from Web.Scotty):
zero-bullshit>     Deprecated: "(#204) Not a good idea to treat all parameters identically. Use captureParams, formParams and queryParams instead. "
zero-bullshit>     |
zero-bullshit> 172 |   params <- (fmap textToString) <$> Scotty.params
zero-bullshit>     |                                     ^^^^^^^^^^^^^

Error: [S-7282]
       Stack failed to execute the build plan.
       
       While executing the build plan, Stack encountered the error:
       
       [S-7011]
       While building package zero-bullshit-0.1.0.0 (scroll up to its section to see the error)
       using:
       /home/akari/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_DY68M0FN_3.10.3.0_ghc-9.6.6 --verbose=1 --builddir=.stack-work/dist/x86_64-linux/ghc-9.6.6 build --ghc-options ""
       Process exited with code: ExitFailure 1 
```
